CREATE TABLE "podcastepisode" (
	"uuid" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"hash" text,
	"hash_timestamp" bigint,
	"date_published" timestamp with time zone,
	"name" text,
	"description" text,
	"image_url" text,
	"series_uuid" text,
	"guid" text NOT NULL,
	"series_uuid_plus_guid" text,
	"subtitle" text,
	"audio_url" text,
	"video_url" text,
	"file_length" integer,
	"file_type" text,
	"duration" integer,
	"season_number" integer,
	"episode_number" integer,
	"episode_type" text,
	"website_url" text,
	"is_explicit_content" boolean,
	"is_removed" boolean,
	"series_hash" text,
	"is_blocked" boolean,
	"rss_transcripts" jsonb,
	"rss_chapters" jsonb,
	"rss_persons_hash" text,
	"transcribe_status" text,
	"taddy_transcript_url" text,
	"taddy_chunks_url" text,
	"taddy_chapter_url" text,
	CONSTRAINT "podcastepisode_series_uuid_plus_guid_unique" UNIQUE("series_uuid_plus_guid")
);
--> statement-breakpoint
CREATE TABLE "podcastseries" (
	"uuid" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"source" text,
	"hash" text,
	"hash_timestamp" bigint,
	"genres_hash" text,
	"itunes_info_hash" text,
	"date_published" timestamp with time zone,
	"name" text,
	"description" text,
	"image_url" text,
	"itunes_id" bigint,
	"series_type" text,
	"copyright" text,
	"country_of_origin" text,
	"language" text,
	"website_url" text,
	"author_name" text,
	"content_type" text,
	"rss_url" text,
	"rss_owner_name" text,
	"rss_owner_public_email" text,
	"is_explicit_content" boolean,
	"is_completed" boolean,
	"is_blocked" boolean,
	"children_hash" text,
	"rss_persons_hash" text,
	"transcribe_status" text,
	"genres" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	CONSTRAINT "podcastseries_hash_unique" UNIQUE("hash"),
	CONSTRAINT "podcastseries_itunes_id_unique" UNIQUE("itunes_id"),
	CONSTRAINT "podcastseries_rss_url_unique" UNIQUE("rss_url")
);
