import { pgTable, text, timestamp, boolean, integer, bigint, jsonb } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const podcastseries = pgTable('podcastseries', {
  uuid: text('uuid').primaryKey(),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }),
  source: text('source'),
  hash: text('hash').unique(),
  hashTimestamp: bigint('hash_timestamp', { mode: 'bigint' }),
  genresHash: text('genres_hash'),
  itunesInfoHash: text('itunes_info_hash'),
  datePublished: timestamp('date_published', { withTimezone: true, mode: 'string' }),
  name: text('name'),
  description: text('description'),
  imageUrl: text('image_url'),
  itunesId: bigint('itunes_id', { mode: 'bigint' }).unique(),
  seriesType: text('series_type'),
  copyright: text('copyright'),
  countryOfOrigin: text('country_of_origin'),
  language: text('language'),
  websiteUrl: text('website_url'),
  authorName: text('author_name'),
  contentType: text('content_type'),
  rssUrl: text('rss_url').unique(),
  rssOwnerName: text('rss_owner_name'),
  rssOwnerPublicEmail: text('rss_owner_public_email'),
  isExplicitContent: boolean('is_explicit_content'),
  isCompleted: boolean('is_completed'),
  isBlocked: boolean('is_blocked'),
  childrenHash: text('children_hash'),
  rssPersonsHash: text('rss_persons_hash'),
  transcribeStatus: text('transcribe_status'),
  genres: text('genres').array().notNull().default(sql`ARRAY[]::text[]`),
});

export const podcastepisode = pgTable('podcastepisode', {
  uuid: text('uuid').primaryKey(),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' }),
  hash: text('hash'),
  hashTimestamp: bigint('hash_timestamp', { mode: 'bigint' }),
  datePublished: timestamp('date_published', { withTimezone: true, mode: 'string' }),
  name: text('name'),
  description: text('description'),
  imageUrl: text('image_url'),
  seriesUuid: text('series_uuid'),
  guid: text('guid').notNull(),
  seriesUuidPlusGuid: text('series_uuid_plus_guid').unique(),
  subtitle: text('subtitle'),
  audioUrl: text('audio_url'),
  videoUrl: text('video_url'),
  fileLength: integer('file_length'),
  fileType: text('file_type'),
  duration: integer('duration'),
  seasonNumber: integer('season_number'),
  episodeNumber: integer('episode_number'),
  episodeType: text('episode_type'),
  websiteUrl: text('website_url'),
  isExplicitContent: boolean('is_explicit_content'),
  isRemoved: boolean('is_removed'),
  seriesHash: text('series_hash'),
  isBlocked: boolean('is_blocked'),
  rssTranscripts: jsonb('rss_transcripts'),
  rssChapters: jsonb('rss_chapters'),
  rssPersonsHash: text('rss_persons_hash'),
  transcribeStatus: text('transcribe_status'),
  taddyTranscriptUrl: text('taddy_transcript_url'),
  taddyChunksUrl: text('taddy_chunks_url'),
  taddyChapterUrl: text('taddy_chapter_url'),
});
